### ISSUE TITLE
StrafesNET Library Tracking

### ISSUE THREAD

**Issue by insyri** [rsource-open-source/android#1]
- [ ] [`time        (time_id)`](https://api.strafes.net/#/time/get_time__timeId_)
- [ ] [`time_rank   (time_id)`](https://api.strafes.net/#/time/get_time__timeId__rank)

- [ ] [`recent_time (date?, style?, game?, map?)`](https://api.strafes.net/#/time/get_time_recent)
- [ ] [`recent_wr   (style, game. whitelist?)`](https://api.strafes.net/#/time/get_time_recent_wr)

- [ ] [`maps        (game?, page?)`](https://api.strafes.net/#/map/get_map)
- [ ] [`map_time    (mapid, style?, page?)`](https://api.strafes.net/#/time/get_time_map__mapId_)
- [ ] [`map_wr      (mapid, style)`](https://api.strafes.net/#/time/get_time_map__mapId__wr)

- [ ] [`user        (userid)`](https://api.strafes.net/#/user/get_user__userId_)
- [ ] [`user_time   (userid, map?, style?, game?, page?)`](https://api.strafes.net/#/time/get_time_user__userId_)
- [ ] [`user_wr     (userid, game, style)`](https://api.strafes.net/#/time/get_time_user__userId_)
- [ ] [`user_rank   (userid, style, game,)`](https://api.strafes.net/#/rank/get_rank__userId_)

- [ ] [`rank_top    (style, game, page?)`](https://api.strafes.net/#/rank/get_rank)
